<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectSync.Core\ProjectSync.Core.csproj" />
    <ProjectReference Include="..\ProjectSync.Infrastructure\ProjectSync.Infrastructure.csproj" />
  </ItemGroup>
</Project>
