<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ProjectSync.Core\ProjectSync.Core.csproj" />
    <ProjectReference Include="..\..\src\ProjectSync.Infrastructure\ProjectSync.Infrastructure.csproj" />
  </ItemGroup>
</Project>
